export const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CREATE_ROOM: 'room:create',
  ROOM_CREATED: 'room:created',
  JOIN_ROOM: 'room:join',
  ROOM_JOINED: 'room:joined',
  LEAVE_ROOM: 'room:leave',
  SEND_MESSAGE: 'message:send',
  RECEIVE_MESSAGE: 'message:receive',
  MESSAGE_HISTORY: 'messages:history',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  GET_USER_ROOMS: 'user:rooms:get',
  USER_ROOMS: 'user:rooms',
}
